apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-sonarqube
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "sonarqube"
        - name: POSTGRES_PASSWORD
          value: "sonarqube"
        - name: POSTGRES_DB
          value: "sonarqube"
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
  volumes:
  - name: postgresql-data
    emptyDir: {}
