apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany  # Allows multiple pods/nodes to access the volume
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: "/volume1/proxmox-k8s/sonarqube"
    server: "10.10.50.241"  # Replace with your Synology NAS IP

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nfs-pvc
# spec:
#   accessModes:
#     - ReadWriteMany  # Multiple pods can mount
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: nfs-storage
