apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: "/volume1/proxmox-k8s/sonarqube/data"
    server: "10.10.50.241"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-logs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: "/volume1/proxmox-k8s/sonarqube/logs"
    server: "10.10.50.241"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-extensions-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: "/volume1/proxmox-k8s/sonarqube/extensions"
    server: "10.10.50.241"
