apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: "/mnt/diska/sonarqube/data"  # Correct NFS path
    server: "10.10.50.241"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-logs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: "/mnt/diska/sonarqube/logs"  # Correct NFS path
    server: "10.10.50.241"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-extensions-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: "/mnt/diska/sonarqube/extensions"  # Correct NFS path
    server: "10.10.50.241"
