apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:lts
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: sonar-data
              mountPath: "/data"
            - name: sonar-logs
              mountPath: "/logs"
            - name: sonar-extensions
              mountPath: "/extensions"
      volumes:
        - name: sonar-data
          persistentVolumeClaim:
            claimName: sonar-data-pvc
        - name: sonar-logs
          persistentVolumeClaim:
            claimName: sonar-logs-pvc
        - name: sonar-extensions
          persistentVolumeClaim:
            claimName: sonar-extensions-pvc
